server:
  servlet:
    context-path: "/api"
  port: 9001

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username:
    password:
    url: jdbc:postgresql://localhost:5432/keeptrack
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=3600s
bucket4j:
  cache-to-use: jcache
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      rate-limits:
        - cache-key: getHeader("CF-Connecting-IP") # IP based filter
          bandwidths: # maximum of 5 requests within 10 seconds
            - capacity: 100
              time: 10
              unit: seconds




